IMPORTING MATH MODULES

In [ ]:
x=sqrt(25) #error because math module is not imported

NameError: name 'sqrt' is not defined

In [ ]:
import math
x=math.sqrt(25)
x

5.0

In [ ]:
math.sqrt(15)

3.872983346207417

In [ ]:
print(math.floor(2.9))
print(math.ceil(2.9))

2
3


In [ ]:
print(math.pow(3,2))
print(math.pi)  #these values are constant
print(math.e)

9.0
3.141592653589793
2.718281828459045


In [ ]:
import math as m
m.sqrt(10)

3.1622776601683795

In [ ]:
from math import sqrt,pow
print(pow(2,3))
print(round(pow(2,3)))

8.0
8


User inputfunction in python||Command line input

In [ ]:
x=input()
y=input()
z=x+y
print(z)

4
5
45


In [ ]:
x=input('Enter the 1st number')
y=input('Enter the 2nd number')
z=x+y
print(z)

Enter the 1st number10
Enter the 2nd number5
105


In [ ]:
type(x)
type(y)

str

In [ ]:
x=int(input("enter the 1st number"))
y=int(input("enter the 2nd number"))
z=x+y
z

enter the 1st number10
enter the 2nd number5


15

In [ ]:
ch=input('enter a char')
print(ch)

enter a charhello
hello


In [ ]:
print(ch[0])
print(ch[0])
print(ch[-1])
print(ch[1])


h
h
o
e


In [ ]:
ch=input('enter a char')[0]
print(ch)

enter a charhow are u
h


In [ ]:
ch=input('enter a char')[1:3]
print(ch)

enter a charwhat
ha


In [ ]:
ch=input('enter a char')
ch

enter a charhi


'hi'

JULY-3

In [ ]:
import sys
sys.version

'3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]'

In [ ]:
import numpy as np


In [ ]:
np.__version__

'2.0.2'

In [ ]:
#create list
list=[0,1,2,3,4,5]
list

[0, 1, 2, 3, 4, 5]

In [ ]:
type(list)

list

In [ ]:
arr=np.array(list)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
print(type(arr))
print(type(list))


<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [ ]:
np.arrange(10,30,30,3)

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(200,8)

array([], dtype=int64)

In [ ]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [ ]:
np.zeros(3)


array([0., 0., 0.])

In [ ]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [ ]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
nd=np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [ ]:
nd=np.ones((10,10),dtype=int)
nd

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])