IMPORTING MATH MODULES

In [ ]:
x=sqrt(25) #error because math module is not imported

NameError: name 'sqrt' is not defined

In [ ]:
import math
x=math.sqrt(25)
x

5.0

In [ ]:
math.sqrt(15)

3.872983346207417

In [ ]:
print(math.floor(2.9))
print(math.ceil(2.9))

2
3


In [ ]:
print(math.pow(3,2))
print(math.pi)  #these values are constant
print(math.e)

9.0
3.141592653589793
2.718281828459045


In [ ]:
import math as m
m.sqrt(10)

3.1622776601683795

In [ ]:
from math import sqrt,pow
print(pow(2,3))
print(round(pow(2,3)))

8.0
8


User inputfunction in python||Command line input

In [ ]:
x=input()
y=input()
z=x+y
print(z)

hi
hello
hihello


In [ ]:
x=input('Enter the 1st number')
y=input('Enter the 2nd number')
z=x+y
print(z)

Enter the 1st number10
Enter the 2nd number5
105


In [ ]:
type(x)
type(y)

str

In [ ]:
x=int(input("enter the 1st number"))
y=int(input("enter the 2nd number"))
z=x+y
z

enter the 1st number5
enter the 2nd number6


11

In [ ]:
ch=input('enter a char')
print(ch)

enter a charhello
hello


In [ ]:
print(ch[0])
print(ch[0])
print(ch[-1])
print(ch[1])


h
h
o
e


In [ ]:
ch=input('enter a char')[0]
print(ch)

enter a charwhat
w


In [ ]:
ch=input('enter a char')[1:3]
print(ch)

enter a charwhat
ha


In [ ]:
ch=input('enter a char')
ch

enter a charrun


'run'

JULY-3

In [7]:
import sys
sys.version

'3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0]'

In [8]:
import numpy as np


In [9]:
np.__version__

'2.0.2'

In [10]:
#create list
list=[0,1,2,3,4,5]
list

[0, 1, 2, 3, 4, 5]

In [11]:
type(list)

list

In [12]:
arr=np.array(list)
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
print(type(arr))
print(type(list))


<class 'numpy.ndarray'>
<class 'list'>


In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [17]:
np.arrange(10,30,30,3)

AttributeError: module 'numpy' has no attribute 'arrange'

In [18]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(200,8)

array([], dtype=int64)

In [20]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [21]:
np.zeros(3)


array([0., 0., 0.])

In [22]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [23]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
nd=np.zeros((5,9),dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [29]:
nd=np.ones((10,10),dtype=int)
nd

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [30]:
rand(3,2)random.rand(3)

SyntaxError: invalid syntax (ipython-input-30-1122597523.py, line 1)

In [31]:
random.rand(3)

NameError: name 'random' is not defined

In [32]:
np.random.rand(2)

array([0.64480616, 0.545977  ])

In [33]:
np.random.rand(3)

array([0.33365639, 0.72891476, 0.15744943])

In [34]:
random.rand(3)

NameError: name 'random' is not defined

In [35]:
np.random.randint(3)

1

In [36]:
np.random.randint(3,6)

5

In [37]:
np.random.randint(2,10)

9

In [38]:
np.random.randint(10,40,(10,10))

array([[11, 15, 20, 17, 22, 24, 32, 32, 27, 28],
       [10, 26, 18, 10, 21, 27, 37, 33, 27, 20],
       [27, 25, 39, 10, 36, 15, 35, 39, 13, 15],
       [13, 30, 16, 15, 39, 25, 15, 35, 28, 11],
       [16, 27, 12, 14, 17, 15, 37, 14, 13, 38],
       [27, 19, 38, 13, 25, 34, 29, 31, 37, 21],
       [10, 29, 26, 23, 30, 15, 20, 19, 18, 23],
       [12, 29, 34, 16, 27, 28, 15, 27, 35, 37],
       [36, 12, 25, 31, 21, 28, 33, 14, 15, 10],
       [31, 18, 36, 36, 13, 30, 26, 32, 24, 34]])

In [39]:
m=np.random.randint(10,40,(10,10))
m

array([[18, 32, 38, 39, 17, 38, 31, 26, 20, 11],
       [31, 29, 26, 23, 33, 31, 35, 14, 20, 38],
       [33, 23, 13, 20, 39, 20, 36, 31, 29, 17],
       [23, 24, 37, 24, 20, 24, 23, 11, 12, 36],
       [20, 36, 38, 26, 32, 13, 33, 35, 19, 10],
       [17, 31, 33, 19, 18, 26, 25, 38, 30, 22],
       [37, 34, 15, 14, 20, 19, 28, 24, 20, 22],
       [33, 35, 33, 22, 24, 18, 14, 31, 23, 38],
       [25, 24, 15, 14, 20, 11, 35, 22, 14, 29],
       [31, 28, 38, 19, 21, 25, 28, 19, 25, 14]])

In [40]:
arr

array([0, 1, 2, 3, 4, 5])

In [41]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [43]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [44]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

Slicing in Matrix

In [45]:
m

array([[18, 32, 38, 39, 17, 38, 31, 26, 20, 11],
       [31, 29, 26, 23, 33, 31, 35, 14, 20, 38],
       [33, 23, 13, 20, 39, 20, 36, 31, 29, 17],
       [23, 24, 37, 24, 20, 24, 23, 11, 12, 36],
       [20, 36, 38, 26, 32, 13, 33, 35, 19, 10],
       [17, 31, 33, 19, 18, 26, 25, 38, 30, 22],
       [37, 34, 15, 14, 20, 19, 28, 24, 20, 22],
       [33, 35, 33, 22, 24, 18, 14, 31, 23, 38],
       [25, 24, 15, 14, 20, 11, 35, 22, 14, 29],
       [31, 28, 38, 19, 21, 25, 28, 19, 25, 14]])

In [46]:
b=np.random.randint(10,20,(5,4))
b

array([[14, 11, 12, 10],
       [16, 12, 19, 14],
       [11, 19, 12, 12],
       [19, 17, 19, 10],
       [16, 18, 10, 11]])

In [47]:
type(b)

numpy.ndarray

In [48]:
b[:]

array([[14, 11, 12, 10],
       [16, 12, 19, 14],
       [11, 19, 12, 12],
       [19, 17, 19, 10],
       [16, 18, 10, 11]])

In [49]:
b[1:4]

array([[16, 12, 19, 14],
       [11, 19, 12, 12],
       [19, 17, 19, 10]])

In [50]:
b[-1:]

array([[16, 18, 10, 11]])

In [51]:
b[:-1]

array([[14, 11, 12, 10],
       [16, 12, 19, 14],
       [11, 19, 12, 12],
       [19, 17, 19, 10]])

In [52]:
np.random.randint(10,20,5)

array([12, 16, 13, 18, 14])

In [53]:
np.random.randint(-30,20,10)

array([ 13,  -3, -22, -15, -27,  13, -11,  -7,  -1,  11])

In [54]:
np.random.randint(5,9)

6

In [55]:
np.random.randint(10,21,3)

array([19, 19, 13])

In [56]:
np.random.randint(1,12,10)

array([ 5,  5, 11,  4, 10,  3,  7,  2,  1,  9])

In [57]:
np.random.randint(5,9)

5

In [58]:
np.random.randint(1,100,(12,12))

array([[68, 61, 85, 25, 48, 39, 48, 87, 11,  6,  1, 15],
       [47, 99, 72, 95, 12, 46, 80,  2,  5, 19, 38, 51],
       [25, 22, 58, 18, 79, 53,  6, 62, 81, 22, 13, 27],
       [67, 64, 79, 76, 68, 87, 52, 90, 79,  9,  5,  2],
       [10, 70, 46,  1, 84, 54, 83, 59, 73,  1, 77,  8],
       [20, 65, 12, 86, 86, 32, 63,  8, 44, 89, 49, 95],
       [39, 35, 18, 25, 18, 16, 26, 77, 22, 14, 81, 61],
       [87, 80, 25, 99, 40, 99, 16, 82, 75, 87, 33, 86],
       [59, 44, 57, 48,  4, 71, 14,  9, 67, 22, 32, 63],
       [93, 35,  6, 78, 59, 59, 87, 55, 91, 26,  7, 14],
       [80, 67, 23, 65, 62, 12, 39, 81, 63,  5, 66, 71],
       [28, 48, 32, 85, 47, 46, 44, 94, 29, 86, 64, 18]])

In [59]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [61]:
b=np.random.randint(10,20,(5,4))
b

array([[14, 15, 17, 12],
       [15, 14, 18, 10],
       [10, 11, 17, 12],
       [10, 11, 12, 11],
       [18, 13, 14, 17]])

In [62]:
type(b)

numpy.ndarray

In [63]:
b[1,3]

np.int64(10)

In [64]:
b[1:3]

array([[15, 14, 18, 10],
       [10, 11, 17, 12]])

In [65]:
b[1,2]

np.int64(18)

In [66]:
b[1,-1]

np.int64(10)

In [67]:
b[2:3]

array([[10, 11, 17, 12]])

In [68]:
b[0:-2]

array([[14, 15, 17, 12],
       [15, 14, 18, 10],
       [10, 11, 17, 12]])

In [69]:
b[0:2]

array([[14, 15, 17, 12],
       [15, 14, 18, 10]])

In [70]:
b[-5,-3]

np.int64(15)

In [71]:
b[-4,2]

np.int64(18)

In [72]:
np.random.randint(10,20,(4,4))

array([[18, 16, 10, 15],
       [17, 18, 17, 10],
       [10, 13, 17, 12],
       [14, 11, 17, 11]])

In [73]:
b[-4,-2]

np.int64(18)

In [75]:
a=np.random.randint(10,20,10)
a

array([14, 15, 11, 13, 19, 18, 14, 11, 19, 16])

In [76]:
id(a)

132340618104912

In [77]:
arr

array([0, 1, 2, 3, 4, 5])

In [79]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[35, 38, 76, 33, 36, 10, 24, 40, 20, 43],
       [20, 79, 20, 90, 72, 28, 19, 54, 88, 34],
       [14,  7, 31, 39, 18, 52, 94, 33, 47, 10],
       [85,  8, 14,  3, 86, 27, 28, 61, 50, 48],
       [59, 40, 42, 51,  3, 79, 27, 46, 58, 70],
       [37, 73, 68, 32, 64, 83, 93, 67, 77, 15],
       [96, 46, 98,  4,  6, 74, 22, 62, 86, 85],
       [39, 57, 89, 82, 71, 93,  3, 87, 43, 59],
       [46, 27, 35, 56, 71, 61, 75,  1, 50, 19],
       [24,  0, 83, 80, 37, 85, 98, 65, 31, 62]])

In [80]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [81]:
arr[:4]

array([0, 1, 2, 3])

In [82]:
arr2[:]

array([[35, 38, 76, 33, 36, 10, 24, 40, 20, 43],
       [20, 79, 20, 90, 72, 28, 19, 54, 88, 34],
       [14,  7, 31, 39, 18, 52, 94, 33, 47, 10],
       [85,  8, 14,  3, 86, 27, 28, 61, 50, 48],
       [59, 40, 42, 51,  3, 79, 27, 46, 58, 70],
       [37, 73, 68, 32, 64, 83, 93, 67, 77, 15],
       [96, 46, 98,  4,  6, 74, 22, 62, 86, 85],
       [39, 57, 89, 82, 71, 93,  3, 87, 43, 59],
       [46, 27, 35, 56, 71, 61, 75,  1, 50, 19],
       [24,  0, 83, 80, 37, 85, 98, 65, 31, 62]])

In [83]:
arr2[0:5]

array([[35, 38, 76, 33, 36, 10, 24, 40, 20, 43],
       [20, 79, 20, 90, 72, 28, 19, 54, 88, 34],
       [14,  7, 31, 39, 18, 52, 94, 33, 47, 10],
       [85,  8, 14,  3, 86, 27, 28, 61, 50, 48],
       [59, 40, 42, 51,  3, 79, 27, 46, 58, 70]])

In [84]:
arr2[1,4]

np.int64(72)

In [85]:
arr2[-5,5]

np.int64(83)

In [86]:
arr2[-1,-2]

np.int64(31)

In [87]:
arr2[::-1]

array([[24,  0, 83, 80, 37, 85, 98, 65, 31, 62],
       [46, 27, 35, 56, 71, 61, 75,  1, 50, 19],
       [39, 57, 89, 82, 71, 93,  3, 87, 43, 59],
       [96, 46, 98,  4,  6, 74, 22, 62, 86, 85],
       [37, 73, 68, 32, 64, 83, 93, 67, 77, 15],
       [59, 40, 42, 51,  3, 79, 27, 46, 58, 70],
       [85,  8, 14,  3, 86, 27, 28, 61, 50, 48],
       [14,  7, 31, 39, 18, 52, 94, 33, 47, 10],
       [20, 79, 20, 90, 72, 28, 19, 54, 88, 34],
       [35, 38, 76, 33, 36, 10, 24, 40, 20, 43]])

In [89]:
arr2[::-2]

array([[24,  0, 83, 80, 37, 85, 98, 65, 31, 62],
       [39, 57, 89, 82, 71, 93,  3, 87, 43, 59],
       [37, 73, 68, 32, 64, 83, 93, 67, 77, 15],
       [85,  8, 14,  3, 86, 27, 28, 61, 50, 48],
       [20, 79, 20, 90, 72, 28, 19, 54, 88, 34]])

In [90]:
arr2[::-3]

array([[24,  0, 83, 80, 37, 85, 98, 65, 31, 62],
       [96, 46, 98,  4,  6, 74, 22, 62, 86, 85],
       [85,  8, 14,  3, 86, 27, 28, 61, 50, 48],
       [35, 38, 76, 33, 36, 10, 24, 40, 20, 43]])

In [91]:
arr2

array([[35, 38, 76, 33, 36, 10, 24, 40, 20, 43],
       [20, 79, 20, 90, 72, 28, 19, 54, 88, 34],
       [14,  7, 31, 39, 18, 52, 94, 33, 47, 10],
       [85,  8, 14,  3, 86, 27, 28, 61, 50, 48],
       [59, 40, 42, 51,  3, 79, 27, 46, 58, 70],
       [37, 73, 68, 32, 64, 83, 93, 67, 77, 15],
       [96, 46, 98,  4,  6, 74, 22, 62, 86, 85],
       [39, 57, 89, 82, 71, 93,  3, 87, 43, 59],
       [46, 27, 35, 56, 71, 61, 75,  1, 50, 19],
       [24,  0, 83, 80, 37, 85, 98, 65, 31, 62]])

In [92]:
arr2[:-3]

array([[35, 38, 76, 33, 36, 10, 24, 40, 20, 43],
       [20, 79, 20, 90, 72, 28, 19, 54, 88, 34],
       [14,  7, 31, 39, 18, 52, 94, 33, 47, 10],
       [85,  8, 14,  3, 86, 27, 28, 61, 50, 48],
       [59, 40, 42, 51,  3, 79, 27, 46, 58, 70],
       [37, 73, 68, 32, 64, 83, 93, 67, 77, 15],
       [96, 46, 98,  4,  6, 74, 22, 62, 86, 85]])

In [94]:
arr.max()

np.int64(5)

In [95]:
arr.min()

np.int64(0)

In [96]:
arr.mean()

np.float64(2.5)

In [97]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [100]:
from numpy import *
a=array([1,2,3,4,5])
median(a)

np.float64(3.0)

In [101]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [102]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [103]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [104]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [105]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [106]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [107]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [108]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [109]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [111]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [112]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [113]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [114]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

Indexing

In [116]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
row=4
col=5

In [118]:
col

5

In [119]:
row

4

In [120]:
mat[row,col]

np.int64(45)

In [134]:
mat[4,5]

np.int64(45)

In [135]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [136]:
col=6

In [137]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [138]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [139]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [140]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [141]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [142]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [143]:
row

4

In [144]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [145]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [146]:
mat[1:2,2:4]

array([[12, 13]])

In [147]:
mat[2:3,2:3]

array([[22]])

In [148]:
mat[2:3]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [149]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [150]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [151]:
mat[2:3,4:5]

array([[24]])

Masking

In [152]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [153]:
id(mat)

132340613933424

In [154]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [155]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [156]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [157]:
mat[mat==50]

array([50])

In [158]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [160]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [161]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [166]:
list=['a','b','g','1','5']
print(list.pop())

5


In [164]:
x=[1,2,3,4]
y=x.copy()
x.append(5)
x

[1, 2, 3, 4, 5]